spring:
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/task_manager
    driver-class-name: org.postgresql.Driver
  jackson:
    date-format: yyyy-MM-dd
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
